#----------------------
# About section

blurb: <p><strong>Welcome! This is the website for the PsyBORG lab (Psychiatrty Biostatistic Opitimized Research Gadgets lab). We are a research lab in the department of psychiatry at the Washington Univeristy School of Medicine. We are located in St. Louis, Missouri. 
The PsychBORG lab is led by Professor Alexander S. Hatoum. </p>


#----------------------
# Contact
contact-info: <p>Alexander S. Hatoum<br> Washington University School of Medicine <br>Department of Psychiatry<br>St. Louis<br>Missouri<br>WC2R 2LS<br>USA</p>

contact-links:
  - {contact-text: ashatoum@wustl.edu, contact-link: "https://scholar.google.com/citations?user=VkJlMN0AAAAJ&hl=en&oi=ao", icon: 'favicon.html'}
